### ISSUE TITLE
Strange installation in MacOS 12.6

### ISSUE THREAD

**Issue by mars0i** [mastotron/mastotron#11]
Followed the instructions for MacOS.  Apparently in 12.6, the popup warning about malicious software is can't be circumvented by clicking on open.  MacOS just said it can't check the binary so I can't run Mastotron.  That was running it from my download directory.  So then I moved it to /Applications (not using Finder, but using Unix 'mv'), and Mastotron instantly opened--which was weird.  I didn't enter '/Applications/Mastrotron' or anything like that on the command line, and didn't click on it in Finder at that point.  No complaints--just passing this on in case it's helpful.

Based on the video, this looks amazing.

**Comment by quadrismegistus** [comment]
Glad it worked! Thanks for this note. I've added a line to the readme about the /Applications folder. Closing this for now but let me know if any other strange things arise!
