### ISSUE TITLE
Debian 11 with mate (tailored) 

### ISSUE THREAD

**Issue by giormatsis** [mastotron/mastotron#13]
Not opening with double click nor in commant line.
![Screenshot at 2023-02-11 07-38-53](https://user-images.githubusercontent.com/8190053/218195328-d47a0a87-e927-4fc6-a73c-cf9868b137f8.png)

**Comment by quadrismegistus** [comment]
Closing to consolidate similar issues. See https://github.com/mastotron/mastotron/issues/22 now instead.
